CATALOG: ./hyp/*.hyp
RESULTS: ./results
WAVEFORMS: ./events
FORMAT: FUB2018
STATIONS: stations.nll
VELOCITIES:
    - vmodel.zv
LOGGING: WARNING
dang: 1
nmc: 50
maxout: 100
cangle: 45
prob_max: 0.2
qbadfac: 0.2
